Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapStone.Models;
using System.Data.Entity;

namespace CapStone.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Configuration;
using System.Data.OleDb;
using CapStone.Models;


namespace CapStone.Controllers
{
    public class MemberController : Controller
    {
        private MemberModel client = new MemberModel();
        private RolesModel db = new RolesModel();
        // GET: Member
        public ActionResult Index()
        {
            return View();
        }

        // GET: Member/Create
        public ActionResult Register()
        {
            //var getclass = ["admin", "member"];
            //SelectList list = new SelectList(getclass);
            //ViewBag.SelectClass = list;
            return View();
        }

        // POST: Member/Create
        [HttpPost]
        public ActionResult Register([Bind(Exclude = "Id")] Member NewMember)
        {
            try
            {
                // TODO: Add insert logic here

                NewMember.Password = FormsAuthentication.HashPasswordForStoringInConfigFile(NewMember.Password, "SHA1");
                var getMember = client.Members.Where(n => n.Email == NewMember.Email && n.Password == NewMember.Password).FirstOrDefault();

                if (getMember!=null)
                {
                    ViewBag.NotAdded = "Member already exists, login instead";
                    return View("Register");
                }

                client.Members.Add(NewMember);
                client.SaveChanges();
                var getM = client.Members.Where(n => n.Email == NewMember.Email && n.Password == NewMember.Password).FirstOrDefault();

                Role newRole = new Role();
                newRole.Role1 = "user";
                newRole.userId = getM.Id;
                db.Roles.Add(newRole);
                db.SaveChanges();

                //NewMember.Type = "member";
              
                ModelState.Clear();
                return RedirectToAction("Index","Home");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Login()
        {
            return View();
        }

        // POST: Member/Create
        [HttpPost]
        public ActionResult Login(Member NewMember, string returnUrl)
        {
            
            
                // TODO: Add insert logic here
                string hashedpasswrd = FormsAuthentication.HashPasswordForStoringInConfigFile(NewMember.Password, "SHA1");
                var getMember = client.Members.Where(n => n.Email == NewMember.Email && n.Password == hashedpasswrd).FirstOrDefault();

            Session["logged"] = null;

            if (getMember != null)
            {
                var admin = db.Roles.Where(n => n.userId == getMember.Id && n.Role1 == "admin").FirstOrDefault();
                Session["admin"] = false;
                if (admin != null)
                    Session["admin"] =true;
            

                FormsAuthentication.SetAuthCookie(NewMember.Email, true);
                Session["logged"] = true;

                if (!string.IsNullOrEmpty(returnUrl))
                    return Redirect(returnUrl);
                else
                    return RedirectToAction(controllerName: "Class", actionName: "Index");
               
            }
            else
            {
                ViewBag.Mess = "Invalid username/password";
                return View("Login");
            }
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            Session["logged"] = null;
            Session["isAdmin"] = null;
            return View("Login");
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<p>Contact us at: 087 965 4654 or <a href="mailto:s219620873@mandela.ac.za">v-active@gmail.com</a> </p>

<span>I assumed that admins are preset into the data base all they do is login</span><br />
<span>Only users register using the website</span><br />

<span>For testing: Admin-njabulo@gmail.com, password:123 </span> <br />
<span>for any other user marinda, password marinda or a new registration will be just fine </span>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "V-Avtive:Home";
}

<h2>V-Active </h2>


<h1> "Your Number One Fitness Destination"  </h1>


<div id="content">
    <table class="catalogue">
        <tr>
            <th>Exercise</th>
            <th>Price per class</th>
        </tr>
        <tr>
            <td>Yoga</td>
            <td>R60</td>
        </tr>
        <tr>
            <td>Swimming</td>
            <td>R80</td>
        </tr>
        <tr>
            <td>Cycling</td>
            <td>R50</td>
        </tr>
        <tr>
            <td>Dance</td>
            <td>R150</td>
        </tr>

    </table>
</div>
<span>Note: the prices are charged per person </span>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
       <button type="submit" class="login">@Html.ActionLink("Login", "Login", "Member")</button>
        <button type="submit" class="register">@Html.ActionLink("Register", "Register", "Member")</button>
    </div>
</div>